---
- name: Configuring system
  hosts: arch

  tasks:
    - name: Ensure config directories are created
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "{{ mode }}"
        owner: "{{ username }}"
        group: "{{ group }}"
      loop: "{{ paths }}"
      tags: dirs

    - name: Link dotfiles to respective locations
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ username }}"
        group: "{{ group }}"
        state: link
      loop: "{{ links }}"
      tags: link

    - name: Install missing packages
      become: true
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
      tags: packages

    - name: Check to see if yay is already installed
      ansible.builtin.stat:
        path: /usr/bin/yay
      register: yay_installed
      tags: yay

    - name: Install yay dependencies
      become: true
      ansible.builtin.package:
        name:
          - git
          - base-devel
        state: present
      when: yay_installed.stat.exists == false
      tags: yay

    - name: Clone the yay PKGBUILD
      ansible.builtin.git:
        repo: "{{ yay.repo }}"
        dest: "{{ yay.dest }}"
      when: yay_installed.stat.exists == false
      tags: yay

    - name: Build yay with makepkg
      become: true
      ansible.builtin.shell:
        cmd: makepkg -sic
        chdir: "{{ yay.dest }}"
      when: yay_installed.stat.exists == false
      tags: yay

    - name: Set default shell to zsh
      become: true
      ansible.builtin.shell:
        cmd: "chsh -s /usr/bin/zsh {{ username | ansible.builtin.quote }}"
      when: ansible_facts.user_shell != "/usr/bin/zsh"
      tags: zsh

    - name: Install zsh plugins
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
      loop: "{{ zsh_plugs }}"
      tags: zsh

    - name: Install Packer (neovim plugin manager)
      ansible.builtin.git:
        repo: "{{ packer.repo }}"
        dest: "{{ packer.dest }}"
        depth: "{{ packer.depth }}"
      tags: neovim

