---
- name: Configuring system
  hosts: arch

  tasks:
    - name: Ensure config directories are created
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "{{ mode }}"
        owner: "{{ username }}"
        group: "{{ group }}"
      loop: "{{ paths }}"
      tags: dirs

    - name: Link dotfiles to respective locations
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ username }}"
        group: "{{ group }}"
        state: link
      loop: "{{ links }}"
      tags: link

    - name: Install missing packages
      become: true
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
      tags: packages

    - name: Install zsh plugins
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
      loop: "{{ zsh_plugs }}"
      tags: zsh
