#!/bin/sh

# Define border colors
color0=#3B4252
color1=#D8DEE9

# Launch polybar
bash ~/.config/polybar/launch.sh &

# Launch startup scripts
bash ~/.config/autostart/startup.sh &

# Make sure sxhkd is running for hotkeys
while :; do
  if pgrep -x sxhkd >/dev/null; then
    true
  else
    sxhkd &
  fi
  sleep 5
done &

# Set keyboard layout and default cursor
setxkbmap -layout us
xsetroot -cursor_name left_ptr

# Set window size and padding
bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc config window_gap             8
bspc config border_width           2
bspc config top_padding            4
bspc config right_padding          4
bspc config left_padding           4
bspc config bottom_padding         4
bspc config top_monocle_padding    0
bspc config left_monocle_padding   0
bspc config right_monocle_padding  0
bspc config bottom_monocle_padding 0
bspc config split_ratio            0.50
bspc config borderless_monocle     true
bspc config gapless_monocle        true

# Set border colors
bspc config focused_border_color  "$color0"
bspc config normal_border_color   "$color0"
bspc config active_border_color   "$color0"
bspc config presel_feedback_color "$color1"

# Application rules
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

# Set desktop background
sleep 0.50
nitrogen --set-auto "$HOME/.config/bg.jpg" &

# Start on desktop 1
bspc desktop -f 1
